apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }

        # rewrite name        substring svc.tanzucloud.net svc.cluster.local
        
        rewrite stop {

         name   regex  (.*)\.svc\.tanzucloud\.net   {1}.svc.cluster.local
         answer name   (.*)\.svc\.cluster\.local    {1}.svc.tanzucloud.net

        }

        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system