apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: demo2
  namespace: demo
spec:
  distribution:
    version: v1.18.5
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 192.0.2.0/16
      serviceDomain: tanzucloud.net
      services:
        cidrBlocks:
        - 198.51.100.0/12
  topology:
    controlPlane:
      class: best-effort-xsmall
      count: 1
      storageClass: tanzu
    workers:
      class: best-effort-small
      count: 2
      storageClass: tanzu

