---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: thin-disk
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
      storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: thin