FROM registry.access.redhat.com/ubi8/ubi

MAINTAINER hemanth.avs@gmail.com

RUN yum -y update \
    && yum -y install bind-utils \
    && yum clean all

ADD bellsoft-jdk11.0.9+12-linux-amd64.tar.gz /srv/java

RUN groupadd -g 1001 java \
    && useradd -r -u 1001 -g java java

RUN mkdir /data \
    && chown java:java /data \
    && chown -R java:java /srv/java/jdk-11.0.9

ENV PATH=/srv/java/jdk-11.0.9/bin:/srv/java/jdk-11.0.9:$PATH 
USER java
