apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-test
  namespace: test
spec:
  secretName: nginx-test
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'cm.tanzucloud.net'