apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hemanthavs@vmware.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "tanzucloud.net"
      dns01:
        route53:
          region: us-east-1
          accessKeyID: test
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key